apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: multi-tenancy-gitops
    group: pipeline
    type: git
  name: gitops-repo
data:
  branch: master
  host: github.com
  org: dt-prod-base
  owner: dt-prod-base
  parentdir: .
  protocol: https
  repo: multi-tenancy-gitops-apps
  url: https://github.com/dt-prod-base/multi-tenancy-gitops-apps.git
