apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ibm-entitled-registry-credentials
  namespace: ci
spec:
  encryptedData:
    IBM_ENTITLED_REGISTRY_PASSWORD: AgAFi7sZFeVBwek9KCV0DeuaqFeaStSp7ZHsr7+aHmWIg6UFbe2naH5Wdi8TpBGyKplsG0BeqbCh+BvTQdzEZ/Bmrb7zQC+7R/OFh2qEdsk82xZQJV1ynXpHRXBw4RcM9BiBLZQKS/+daenvZSXolTks9HCmhH/hwMb0WccMr5rf1RBW/icjUcEUdLSESUD4muecclDhhq3hbeCyYCL1+ysMAunSwSyOwqYB9HVfLe5WV/7KvDCZ+8kR9xNQP7n6+auBQdzyyiL1OkPAbF9BUuVirHnKR4Dqt+MaPMmYpQJoxoFJJEDVPZyXWwEdTTwx32ugfCQ3WpxfiWprXRlrqGoePAlqmDxpJGOUq6heYVCUYmRLRQc3bNtKRtN1bxbtRAS9xEfgrzJ3CC5/06veFZRfwlc3NccR0+PMehhiVxmYSbrT1O/3p9B3/+ig9xYMP0G6UJ2EXjZmX0RD+PqUE6z+uU+r5PBWmopzqIl7LQOf66Hx32J3UNLs+Kxn6WPTrBD1CehAvRbzOlMUPP2aXVWDyAFlp7y8oZMwyNG6eA2235zz4rS+QfUzbyPbgmlbidDnoXNfwx23EhQLkNkQDbAOEYslTJTDIV/zLsOHqWCcwGmpYPZwgWmu7pQ9sLBhhG6odx4VMyewq/hZttIM5hIocbPKv7GykK7vWJj8tiqHzkmM3tbxb/QiSLl370A+ISDrvI9fugLTpPk3CvuAkk3SRjDtE4jGPwiTmpYbVll6iakn1BnZSXHQmxAn8m6qjXMHT8A+1RWm8dGetmmEhjhQtKfgHr0O6rmPXchIQaaiWePO7bEEsoHF1yJ39wg8KZuFv8a1NPd5+CFqaO3W3/x4Og/uUCTJHXa2wfuAG4gCvAB8nzqynKvJfVo+usMrJtPnvMbn5bc4HuWRgO7UUItMosbiTMuTIvRVyiwFAKDOig==
    IBM_ENTITLED_REGISTRY_USER: AgDHG19TU1flZZgVmeW7KFZPzOSlReaL/hdecdnFV150nNhx14HneXvvYT4QT2tbuqb40euXi6w3udlmjIvF8w4VrBnJPf0xVlWDX70XDvl2Ixpw4K6e67OrnEwZUgrasxAwZKaWCBINmmdu+PoFm9zcqNLgv5+Y4FaHXTxAZemglBL+WYW1LO5kGzfx/aksGq6TVpAackCVBCqh/kUPAjKqvJX5C1aRokU5klmyWpsyoTVHRHwmhHAwoVHlRm/aObrvyXY9Ul4QLsyZfAr7xFywoffIxPDJ6BCHqoqK+GEJFTp0m6FMiMHQFgO+IuWpUXP9Zoc9jMWbWTNOHhxCDhgYFBrLRyZ+bne6qjw6HUsI5DGwKLWqdbrfPTSkSyZXk/dEMgk7sYYfMlg4epiwd45yaWgOdLT5L5a0n/7Xcou8acsrnrm8l+wnTpHYkfeVJEiU4MqD8mDQDE+A8aXgRjzV2BhuDc7OaKvEzh0dK65ImwijkIm6piZ1l5neaRKtsYvVVT9jpkP2EEztX1mgHCp8ZuJdg4dPWzmgXDaikwU4F4OJozhRLUYKDzoC4tfd5Ro+QrqLGBwOLvAHIQkglg6+/c50wj5OQMwgdsoQmhKxYT8ZcgYt8sjU2KcztReiBnyh77YtcBcw1ZJ+9e00XQmPiBW650ajk4MlgUtQ3rII7trgsrnjLhkCd92J3FOoziy7Vw==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: ibm-entitled-registry-credentials
      namespace: ci

